apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: queryservices.gigaspaces.com
spec:
  group: gigaspaces.com   # group name to use for REST API: /apis/<group>/<version>
  # either Namespaced or Cluster
  scope: Namespaced
  versions:  # list of versions supported by this CustomResourceDefinition
    - name: v1
      served: true   # Each version can be enabled/disabled by Served flag.
      storage: true  # One and only one version must be marked as the storage version.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                deploymentStatus:
                  type: string
                generation:
                  type: integer
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                image:
                  type: string
                sqlTemplate:
                  type: string
                spaceName:
                  type: string
                replicas:
                  type: integer
                description:
                  type: string
                port:
                  type: integer
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: queryservices
    # singular name to be used as an alias on the CLI and for display
    singular: queryservice
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: QueryService
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - qsvc