# Default values for service-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: service-operator
autoscaling:
  enabled: true
replicaCount: 1

image:
  repository: sapirgilad/operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 311

imagePullSecrets:
  - name: "docker-secret"

service:
  type: ClusterIP
  port: 8080
